# Generated by Django 5.1 on 2024-09-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
