# Generated by Django 5.1 on 2024-09-06 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_reputation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_offered', models.CharField(max_length=255)),
                ('skill_needed', models.CharField(max_length=255)),
                ('swap_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('canceled', 'Canceled')], default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Swap History',
                'verbose_name_plural': 'Swap Histories',
                'ordering': ['-swap_date'],
            },
        ),
    ]
